/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonPost {
        "text": string;
    }
    interface GkHoly {
    }
    interface HomePost {
    }
    interface MenuStx {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PostCard {
        "content": string;
        "titulo": string;
    }
    interface ScrollAni {
        /**
          * How far the element moves in the animation (% of element width/height)
         */
        "animationDistance": string;
        /**
          * How long to delay the animation (ms)
         */
        "delay": number;
        /**
          * Direction the element moves when animating in
         */
        "direction": "up" | "down" | "right" | "left";
        /**
          * How long the animation runs (ms)
         */
        "duration": number;
        /**
          * How much of the element must be visible before it animates (% of element height)
         */
        "triggerDistance": string;
    }
}
declare global {
    interface HTMLButtonPostElement extends Components.ButtonPost, HTMLStencilElement {
    }
    var HTMLButtonPostElement: {
        prototype: HTMLButtonPostElement;
        new (): HTMLButtonPostElement;
    };
    interface HTMLGkHolyElement extends Components.GkHoly, HTMLStencilElement {
    }
    var HTMLGkHolyElement: {
        prototype: HTMLGkHolyElement;
        new (): HTMLGkHolyElement;
    };
    interface HTMLHomePostElement extends Components.HomePost, HTMLStencilElement {
    }
    var HTMLHomePostElement: {
        prototype: HTMLHomePostElement;
        new (): HTMLHomePostElement;
    };
    interface HTMLMenuStxElement extends Components.MenuStx, HTMLStencilElement {
    }
    var HTMLMenuStxElement: {
        prototype: HTMLMenuStxElement;
        new (): HTMLMenuStxElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPostCardElement extends Components.PostCard, HTMLStencilElement {
    }
    var HTMLPostCardElement: {
        prototype: HTMLPostCardElement;
        new (): HTMLPostCardElement;
    };
    interface HTMLScrollAniElement extends Components.ScrollAni, HTMLStencilElement {
    }
    var HTMLScrollAniElement: {
        prototype: HTMLScrollAniElement;
        new (): HTMLScrollAniElement;
    };
    interface HTMLElementTagNameMap {
        "button-post": HTMLButtonPostElement;
        "gk-holy": HTMLGkHolyElement;
        "home-post": HTMLHomePostElement;
        "menu-stx": HTMLMenuStxElement;
        "my-component": HTMLMyComponentElement;
        "post-card": HTMLPostCardElement;
        "scroll-ani": HTMLScrollAniElement;
    }
}
declare namespace LocalJSX {
    interface ButtonPost {
        "text"?: string;
    }
    interface GkHoly {
    }
    interface HomePost {
    }
    interface MenuStx {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PostCard {
        "content"?: string;
        "titulo"?: string;
    }
    interface ScrollAni {
        /**
          * How far the element moves in the animation (% of element width/height)
         */
        "animationDistance"?: string;
        /**
          * How long to delay the animation (ms)
         */
        "delay"?: number;
        /**
          * Direction the element moves when animating in
         */
        "direction"?: "up" | "down" | "right" | "left";
        /**
          * How long the animation runs (ms)
         */
        "duration"?: number;
        /**
          * How much of the element must be visible before it animates (% of element height)
         */
        "triggerDistance"?: string;
    }
    interface IntrinsicElements {
        "button-post": ButtonPost;
        "gk-holy": GkHoly;
        "home-post": HomePost;
        "menu-stx": MenuStx;
        "my-component": MyComponent;
        "post-card": PostCard;
        "scroll-ani": ScrollAni;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-post": LocalJSX.ButtonPost & JSXBase.HTMLAttributes<HTMLButtonPostElement>;
            "gk-holy": LocalJSX.GkHoly & JSXBase.HTMLAttributes<HTMLGkHolyElement>;
            "home-post": LocalJSX.HomePost & JSXBase.HTMLAttributes<HTMLHomePostElement>;
            "menu-stx": LocalJSX.MenuStx & JSXBase.HTMLAttributes<HTMLMenuStxElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "post-card": LocalJSX.PostCard & JSXBase.HTMLAttributes<HTMLPostCardElement>;
            "scroll-ani": LocalJSX.ScrollAni & JSXBase.HTMLAttributes<HTMLScrollAniElement>;
        }
    }
}
