/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ScrollAni {
        /**
          * How far the element moves in the animation (% of element width/height)
         */
        "animationDistance": string;
        /**
          * How long to delay the animation (ms)
         */
        "delay": number;
        /**
          * Direction the element moves when animating in
         */
        "direction": "up" | "down" | "right" | "left";
        /**
          * How long the animation runs (ms)
         */
        "duration": number;
        /**
          * How much of the element must be visible before it animates (% of element height)
         */
        "triggerDistance": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLScrollAniElement extends Components.ScrollAni, HTMLStencilElement {
    }
    var HTMLScrollAniElement: {
        prototype: HTMLScrollAniElement;
        new (): HTMLScrollAniElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "scroll-ani": HTMLScrollAniElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ScrollAni {
        /**
          * How far the element moves in the animation (% of element width/height)
         */
        "animationDistance"?: string;
        /**
          * How long to delay the animation (ms)
         */
        "delay"?: number;
        /**
          * Direction the element moves when animating in
         */
        "direction"?: "up" | "down" | "right" | "left";
        /**
          * How long the animation runs (ms)
         */
        "duration"?: number;
        /**
          * How much of the element must be visible before it animates (% of element height)
         */
        "triggerDistance"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "scroll-ani": ScrollAni;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "scroll-ani": LocalJSX.ScrollAni & JSXBase.HTMLAttributes<HTMLScrollAniElement>;
        }
    }
}
